"""Add Rental and Price table in database

Revision ID: 22acc4eca39c
Revises: 5c6298600b7e
Create Date: 2023-04-17 20:01:53.476948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22acc4eca39c'
down_revision = '5c6298600b7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Rental',
    sa.Column('rental_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('rental_balance', sa.Float(precision=15, decimal_return_scale=2), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('apartment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['apartment_id'], ['Apartment.property_id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['Tenant.person_id'], ),
    sa.PrimaryKeyConstraint('rental_id')
    )
    op.create_table('Price',
    sa.Column('price_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rent', sa.Float(precision=15, decimal_return_scale=2), nullable=False),
    sa.Column('charge', sa.Float(precision=15, decimal_return_scale=2), nullable=False),
    sa.Column('security_deposit', sa.Float(precision=15, decimal_return_scale=2), nullable=False),
    sa.Column('rental_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rental_id'], ['Rental.rental_id'], ),
    sa.PrimaryKeyConstraint('price_id')
    )
    with op.batch_alter_table('Apartment', schema=None) as batch_op:
        batch_op.alter_column('living_area',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=15, decimal_return_scale=4),
               existing_nullable=False)

    with op.batch_alter_table('Tenant', schema=None) as batch_op:
        batch_op.alter_column('annual_salary',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=15, decimal_return_scale=2),
               existing_nullable=False)
        batch_op.alter_column('balance',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=15, decimal_return_scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Tenant', schema=None) as batch_op:
        batch_op.alter_column('balance',
               existing_type=sa.Float(precision=15, decimal_return_scale=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('annual_salary',
               existing_type=sa.Float(precision=15, decimal_return_scale=2),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('Apartment', schema=None) as batch_op:
        batch_op.alter_column('living_area',
               existing_type=sa.Float(precision=15, decimal_return_scale=4),
               type_=sa.REAL(),
               existing_nullable=False)

    op.drop_table('Price')
    op.drop_table('Rental')
    # ### end Alembic commands ###
