"""Add Tenant table in db

Revision ID: 5c6298600b7e
Revises: ce80c54433e9
Create Date: 2023-04-15 11:08:33.710080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c6298600b7e'
down_revision = 'ce80c54433e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tenant',
    sa.Column('social_security_number', sa.String(length=50), nullable=False),
    sa.Column('annual_salary', sa.Float(precision=15, decimal_return_scale=2), nullable=False),
    sa.Column('balance', sa.Float(precision=15, decimal_return_scale=2), nullable=True),
    sa.Column('person_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('birthday', sa.DateTime(), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['Address.address_id'], ),
    sa.PrimaryKeyConstraint('person_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    with op.batch_alter_table('Apartment', schema=None) as batch_op:
        batch_op.alter_column('living_area',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=15, decimal_return_scale=4),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Apartment', schema=None) as batch_op:
        batch_op.alter_column('living_area',
               existing_type=sa.Float(precision=15, decimal_return_scale=4),
               type_=sa.REAL(),
               existing_nullable=False)

    op.drop_table('Tenant')
    # ### end Alembic commands ###
