"""Add and SecurityDeposit table  in database V5

Revision ID: 5e14482db1b0
Revises: bef449e030df
Create Date: 2023-04-22 17:02:01.447988

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5e14482db1b0'
down_revision = 'bef449e030df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('Payment')
    op.execute('DROP TABLE IF EXISTS Payment CASCADE')
    with op.batch_alter_table('Apartment', schema=None) as batch_op:
        batch_op.alter_column('living_area',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=15, decimal_return_scale=4),
               existing_nullable=False)

    with op.batch_alter_table('Price', schema=None) as batch_op:
        batch_op.alter_column('rent',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=15, decimal_return_scale=2),
               existing_nullable=False)
        batch_op.alter_column('charge',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=15, decimal_return_scale=2),
               existing_nullable=False)
        batch_op.alter_column('security_deposit',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=15, decimal_return_scale=2),
               existing_nullable=False)

    with op.batch_alter_table('Rental', schema=None) as batch_op:
        batch_op.alter_column('rental_balance',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=15, decimal_return_scale=2),
               existing_nullable=False)

    with op.batch_alter_table('SecurityDeposit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Float(precision=15, decimal_return_scale=2), nullable=False))
        batch_op.add_column(sa.Column('payment_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('rental_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('SecurityDeposit_payment_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Rental', ['rental_id'], ['rental_id'])
        batch_op.drop_column('security_deposit_id')

    with op.batch_alter_table('Tenant', schema=None) as batch_op:
        batch_op.alter_column('annual_salary',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=15, decimal_return_scale=2),
               existing_nullable=False)
        batch_op.alter_column('balance',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=15, decimal_return_scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Tenant', schema=None) as batch_op:
        batch_op.alter_column('balance',
               existing_type=sa.Float(precision=15, decimal_return_scale=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('annual_salary',
               existing_type=sa.Float(precision=15, decimal_return_scale=2),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('SecurityDeposit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('security_deposit_id', sa.INTEGER(), server_default=sa.text('nextval(\'"SecurityDeposit_security_deposit_id_seq"\'::regclass)'), autoincrement=True, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('SecurityDeposit_payment_id_fkey', 'Payment', ['payment_id'], ['payment_id'])
        batch_op.drop_column('rental_id')
        batch_op.drop_column('payment_date')
        batch_op.drop_column('amount')

    with op.batch_alter_table('Rental', schema=None) as batch_op:
        batch_op.alter_column('rental_balance',
               existing_type=sa.Float(precision=15, decimal_return_scale=2),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('Price', schema=None) as batch_op:
        batch_op.alter_column('security_deposit',
               existing_type=sa.Float(precision=15, decimal_return_scale=2),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('charge',
               existing_type=sa.Float(precision=15, decimal_return_scale=2),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('rent',
               existing_type=sa.Float(precision=15, decimal_return_scale=2),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('Apartment', schema=None) as batch_op:
        batch_op.alter_column('living_area',
               existing_type=sa.Float(precision=15, decimal_return_scale=4),
               type_=sa.REAL(),
               existing_nullable=False)

    op.create_table('Payment',
    sa.Column('payment_id', sa.INTEGER(), server_default=sa.text('nextval(\'"Payment_payment_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('amount', sa.REAL(), autoincrement=False, nullable=False),
    sa.Column('payment_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('payment_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('rental_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['rental_id'], ['Rental.rental_id'], name='Payment_rental_id_fkey'),
    sa.PrimaryKeyConstraint('payment_id', name='Payment_pkey')
    )
    # ### end Alembic commands ###
