"""Add Property and Apartment table in db

Revision ID: a6a3f01e4a7b
Revises: f778db12c41c
Create Date: 2023-04-12 21:05:57.071611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6a3f01e4a7b'
down_revision = 'f778db12c41c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Apartment',
    sa.Column('stage', sa.Integer(), nullable=False),
    sa.Column('outdoor', sa.Boolean(), nullable=False),
    sa.Column('property_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=False),
    sa.Column('living_area', sa.Float(precision=15, decimal_return_scale=4), nullable=False),
    sa.Column('rooms', sa.Integer(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['Address.address_id'], ),
    sa.PrimaryKeyConstraint('property_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Apartment')
    # ### end Alembic commands ###
