"""test db upgrade relationship Address

Revision ID: dd3c5073c6c7
Revises: 
Create Date: 2023-03-29 10:21:44.082656

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dd3c5073c6c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('AppUser')
    op.drop_table('Address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Address',
    sa.Column('address_id', sa.INTEGER(), server_default=sa.text('nextval(\'"Address_address_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('street_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('street_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('additional_address', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('zip_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('address_id', name='Address_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('AppUser',
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('person_id', sa.INTEGER(), server_default=sa.text('nextval(\'"AppUser_person_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('birthday', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('address_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['Address.address_id'], name='AppUser_address_id_fkey'),
    sa.PrimaryKeyConstraint('person_id', name='AppUser_pkey'),
    sa.UniqueConstraint('email', name='AppUser_email_key'),
    sa.UniqueConstraint('password', name='AppUser_password_key'),
    sa.UniqueConstraint('phone_number', name='AppUser_phone_number_key')
    )
    # ### end Alembic commands ###
