"""Add AppUser, Address, Person

Revision ID: f778db12c41c
Revises: 
Create Date: 2023-03-30 13:38:58.353039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f778db12c41c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Address',
    sa.Column('address_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('street_name', sa.String(length=100), nullable=False),
    sa.Column('street_number', sa.Integer(), nullable=False),
    sa.Column('additional_address', sa.String(length=50), nullable=True),
    sa.Column('zip_code', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('address_id')
    )
    op.create_table('AppUser',
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('person_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('birthday', sa.DateTime(), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['Address.address_id'], ),
    sa.PrimaryKeyConstraint('person_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('password'),
    sa.UniqueConstraint('phone_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('AppUser')
    op.drop_table('Address')
    # ### end Alembic commands ###
